Add RuboCop RSpec support
palkan/action_policy pull request #138
Opened 2020-11-08 16:21 UTC by pirj

### What is the purpose of this pull request?

Previously, RuboCop RSpec failed to detect RSpec aliases. A number of
cops were failing false offences, and some cops were unable to lint, as
they were skipping locally defined RSpec aliases taking them for
arbitrary blocks and method calls.

See:
 - https://github.com/rubocop-hq/rubocop-rspec/issues/1077
 - https://github.com/rubocop-hq/rubocop-rspec/pull/956
 - https://github.com/palkan/action_policy/issues/103

Example project:

`Gemfile`:
```ruby
# frozen_string_literal: true

source 'https://rubygems.org'

gem 'action_policy', path: '../../action_policy'
gem 'rubocop-rspec'
```

`.rubocop.yml`:
```yaml
AllCops:
  NewCops: enable

require:
  - rubocop-rspec

inherit_gem:
  action_policy: .rubocop-rspec-aliases.yml
```

`spec/policies/a_policy_spec.rb`:
```ruby
 frozen_string_literal: true

RSpec.describe 'A' do
  describe_rule :luck? do
    succeed 'when stars align'
  end
end
```

#### Before

```
$ rubocop
Inspecting 2 files
.C

Offenses:

spec/policies/a_policy_spec.rb:3:1: C: RSpec/EmptyExampleGroup: Empty example group detected.
RSpec.describe 'A' do
^^^^^^^^^^^^^^^^^^

2 files inspected, 1 offense detected
```

#### After

```
$ rubocop
Inspecting 2 files
..

2 files inspected, no offenses detected
```

### What changes did you make? (overview)

 - added an RSpec alias config file that RuboCop is able to load and append to the default RuboCop RSpec alias configuration.
 - added docs on how to tell RuboCop to use those aliases

### Is there anything you'd like reviewers to focus on?

I don't have any real projects using Action Policy handy. Please test this change on a real project.

PR checklist:

- [-] Tests included
- [x] Documentation updated
- [x] Changelog entry added

2020-11-17 11:28 UTC, palkan requested changes
Awesome! Thanks!

Just one request: let's move the config file into the `config/rubocop-rspec.yml` or anything else, just not the project's root folder.

2020-11-17 11:42 UTC, pirj commented
Sounds good, will move in both PRs :+1:

2020-11-17 19:55 UTC, pirj commented
Moved the config and tested again, works.

2020-11-18 12:18 UTC, merged

2020-11-18 12:18 UTC, palkan commented
Thanks!