Added `with_context` qualifier to `have_authorized_scope` matcher
palkan/action_policy pull request #260
Opened 2024-04-05 12:18 UTC by killondark

Hi @palkan. I added `with_context` qualifier to `have_authorized_scope` matcher
Discussed in https://github.com/palkan/action_policy/issues/258

PR checklist:

- [x] Tests included
- [x] Documentation updated

2024-04-05 22:28 UTC, palkan requested changes
Thanks!

Left some comments, please, take a look.

2024-04-05 22:28 UTC, palkan commented on lib/action_policy/testing.rb
> +            actual_context.all? { |key, value| context[key] == value }
We should use the same logic here as for authorization calls: https://github.com/palkan/action_policy/blob/8e6923970a713bde164680df920522e98fff0d9b/lib/action_policy/testing.rb#L29-L33

It covers subsets and RSpec composable matchers.

2024-04-05 22:28 UTC, palkan commented on lib/action_policy/rspec/have_authorized_scope.rb
> +        @context = {}
The default MUST be `nil` (meaning  that we don't want to verify context)

2024-04-05 22:28 UTC, palkan commented on lib/action_policy/testing.rb
> +          @context = policy.authorization_context
We already have `policy` in the state, no need to extract context into its own instance variable.

2024-04-05 22:28 UTC, palkan commented on docs/testing.md
> +  end
A context is usually a record (it's an acting _subject_); it's unlikely a bool. Let's change this example:

```suggestion
  def for_user
    user = User.find(params[:id])
    authorized_scope(User.all, context: {user:})
  end
```

2024-04-05 22:28 UTC, palkan commented on docs/testing.md
> +  .with_context(favorite: true)
```suggestion
expect { get :for_user, params: {id: user.id} }.to have_authorized_scope(:scope)
  .with_scope_options(matching(with_deleted: a_falsey_value))
  .with_context(a_hash_including(user:))
```

2024-04-06 10:53 UTC, killondark commented
Thanks for your comments. Corrected. Please check it.

2024-04-15 07:09 UTC, killondark commented
Hi @palkan. Have you seen my latest fixes?

2024-04-19 17:31 UTC, palkan approved these changes
Thanks!

2024-04-19 17:31 UTC, merged